export type TokenName =
  | 'WDS--TEXT--H1-FONT-SIZE'
  | 'WDS--TEXT--H1-LINE-HEIGHT'
  | 'WDS--TEXT--H2-FONT-SIZE'
  | 'WDS--TEXT--H2-LINE-HEIGHT'
  | 'WDS--TEXT--H3-FONT-SIZE'
  | 'WDS--TEXT--H3-LINE-HEIGHT'
  | 'WDS--TEXT--H4-FONT-SIZE'
  | 'WDS--TEXT--H4-LINE-HEIGHT'
  | 'WDS--TEXT--CONTENT-FONT-SIZE'
  | 'WDS--TEXT--CONTENT-LINE-HEIGHT'
  | 'WDS--COLOR--BACKGROUND'
  | 'WDS--COLOR--FOREGROUND'
  | 'WDS--COLOR--ACCENT'
  | 'WDS--COLOR--ACCENT-CONTRAST'
  | 'WDS--COLOR--SUCCESS'
  | 'WDS--COLOR--ERROR'
  | 'WDS--COLOR--ERROR-CONTRAST'
  | 'WDS--COLOR--WARNING'
  | 'WDS--COLOR--INFO'
  | 'WDS--COLOR--MIX-METHOD'
  | 'WDS--SPACE--100'
  | 'WDS--SPACE--200'
  | 'WDS--SPACE--300'
  | 'WDS--SPACE--400'
  | 'WDS--SPACE--500'
  | 'WDS--SPACE--600'
  | 'WDS--SPACE--700'
  | 'WDS--SPACE--800'
  | 'WDS--SPACE--900'
  | 'WDS--RADII--BASE'
  | 'WDS--ANIMATION--TRANSITION-DURATION'
  | 'WDS--ANIMATION--TRANSITION-TIMING-FUNCTION'
  | 'WDS-BUTTON--BORDER-RADIUS'
  | 'WDS-BUTTON--PADDING-X'
  | 'WDS-BUTTON--PADDING-Y'
  | 'WDS-BUTTON--FOCUS-COLOR'
  | 'WDS-BUTTON--ACCENT--BACKGROUND-COLOR'
  | 'WDS-BUTTON--ACCENT--COLOR'
  | 'WDS-BUTTON--DANGER--BACKGROUND-COLOR'
  | 'WDS-BUTTON--DANGER--COLOR'
  | 'WDS-BUTTON--COLOR-MIX-METHOD'
  | 'WDS-BUTTON--TRANSITION-DURATION'
  | 'WDS-BUTTON--TRANSITION-TIMING-FUNCTION';

export type TokenValue = TokenName | string;

export type Tokens = {
  [key in TokenName]: TokenValue;
}

const tokens = {
  "WDS--TEXT--H1-FONT-SIZE": "48px",
  "WDS--TEXT--H1-LINE-HEIGHT": "1",
  "WDS--TEXT--H2-FONT-SIZE": "34px",
  "WDS--TEXT--H2-LINE-HEIGHT": "1",
  "WDS--TEXT--H3-FONT-SIZE": "24px",
  "WDS--TEXT--H3-LINE-HEIGHT": "1.2",
  "WDS--TEXT--H4-FONT-SIZE": "20px",
  "WDS--TEXT--H4-LINE-HEIGHT": "1.2",
  "WDS--TEXT--CONTENT-FONT-SIZE": "16px",
  "WDS--TEXT--CONTENT-LINE-HEIGHT": "1.35",
  "WDS--COLOR--BACKGROUND": "#fff",
  "WDS--COLOR--FOREGROUND": "#000",
  "WDS--COLOR--ACCENT": "blueviolet",
  "WDS--COLOR--ACCENT-CONTRAST": "#fff",
  "WDS--COLOR--SUCCESS": "green",
  "WDS--COLOR--ERROR": "red",
  "WDS--COLOR--ERROR-CONTRAST": "#fff",
  "WDS--COLOR--WARNING": "yellow",
  "WDS--COLOR--INFO": "blue",
  "WDS--COLOR--MIX-METHOD": "oklab",
  "WDS--SPACE--100": "4px",
  "WDS--SPACE--200": "6px",
  "WDS--SPACE--300": "8px",
  "WDS--SPACE--400": "12px",
  "WDS--SPACE--500": "16px",
  "WDS--SPACE--600": "24px",
  "WDS--SPACE--700": "32px",
  "WDS--SPACE--800": "48px",
  "WDS--SPACE--900": "64px",
  "WDS--RADII--BASE": "4px",
  "WDS--ANIMATION--TRANSITION-DURATION": "0.3s",
  "WDS--ANIMATION--TRANSITION-TIMING-FUNCTION": "ease-in-out",
  // Button
  "WDS-BUTTON--BORDER-RADIUS": "WDS--RADII--BASE",
  "WDS-BUTTON--PADDING-X": "WDS--SPACE--500",
  "WDS-BUTTON--PADDING-Y": "WDS--SPACE--500",
  "WDS-BUTTON--FOCUS-COLOR": "WDS--COLOR--ACCENT",
  "WDS-BUTTON--ACCENT--BACKGROUND-COLOR": "WDS--COLOR--ACCENT",
  "WDS-BUTTON--ACCENT--COLOR": "WDS--COLOR--ACCENT-CONTRAST",
  "WDS-BUTTON--DANGER--BACKGROUND-COLOR": "WDS--COLOR--ERROR",
  "WDS-BUTTON--DANGER--COLOR": "WDS--COLOR--ERROR-CONTRAST",
  "WDS-BUTTON--COLOR-MIX-METHOD": "WDS--COLOR--MIX-METHOD",
  "WDS-BUTTON--TRANSITION-DURATION": "WDS--ANIMATION--TRANSITION-DURATION",
  "WDS-BUTTON--TRANSITION-TIMING-FUNCTION": "WDS--ANIMATION--TRANSITION-TIMING-FUNCTION",
} satisfies Tokens;

export default tokens;
